### ISSUE TITLE
Bug: "Compiled with warnings." message when compiling the code for the first time

### ISSUE THREAD

**Issue by SantiagoJimenezQ** [buildspace/waveportal-starter-project#2]
**Description:**
When compiling the code for the first time, the compiler shows a warning ¨Compiled with warnings.¨. 
For local development this is not a problem, but when trying to deploy it to "Vercel", it will not accept a build with warnings, which can cause some friction to new users.

```
Compiled with warnings.

./src/App.js
  Line 2:10:  'ethers' is defined but never used                                                                                          no-unused-vars
  Line 15:9:  Emojis should be wrapped in <span>, have role="img", and have an accessible description with aria-label or aria-labelledby  jsx-a11y/accessible-emoji
```

**Problems:**
- 'ethers' is defined but never used.
- Emojis should be wrapped in <span>.

**Comment by stevedsimkins** [comment]
Actually a simpler way to solve this is to use the environmental variables in Vercel deployment. For the "NAME" you can use "CI" and the "VALUE" you can use "false." This will ignore those warnings and deploy it!
